language: java
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk17
before_cache:
  - rm --force             $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm --force --recursive $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
